[packages]
winget = [
  "Git.Git",
  "GitHub.cli",
  "Microsoft.WindowsTerminal",
  "Microsoft.VisualStudioCode",
  "Microsoft.PowerShell",
  "Volta.Volta",
  "astral-sh.uv",
  "ajeetdsouza.zoxide",
  "Discord.Discord",
  "OpenWhisperSystems.Signal",
  "Mozilla.Firefox",
  "JanDeDobbeleer.OhMyPosh",
  "RedHat.Podman",
  "RedHat.Podman-Desktop"
]